### PR TITLE
initial readme

### PR DESCRIPTION
**Pull request by MATTERealise**
hey, its Simon. Sorry it's taking so long for me to add the docs. Hopefully this will be enough readme to get people started. The links to the gifs should work once it is in your branch (but don't in mine because the links would be wrong). I'm new to most of the version control stuff so please explain if I need to do anything differently.

### CODE REVIEW

**Comment by MitjaNemec** [comment]
Thanks for your contribution. I've also slightly updated the readme with installation instructions and a brief mention of additional feature. And this is a perfect example why maintaining the documentation is a real PITA. Given that I've managed to update the plugin recently (#3) the graphics you've made should be updated. And I know that preparing the graphics really takes a lot of time and effort.

Now, don't get me wrong. I don't think that updating the graphics is critical. I'd defer it for a couple of months as I expect the plugin might be updated in the near future. Since V6 with PCM, plugins have much better discoverability, so I expect more users will try them out and propose new features and/or find more bugs

**Comment by SimonMerrett** [comment]
Darn, I updated the plugin just before making the graphics last night! I thought I saw the rotate every nth component but I guess not the way #3 implements.

I'll move on to another repo next. Do you think Replicate Layout is ready? It was buggy for me earlier this week. Or do you have a higher priority?

**Comment by MitjaNemec** [comment]
Regarding the Replicate Layout, what was buggy? I did receive a couple of issues, but critical ones should have been resolved.

If you have reservations you might want to start on [Archive 3D Models](https://github.com/MitjaNemec/Archive3DModels).

Also with regards to documentation, obviously a README.md is a must, but that can bi minimal. I can give you write acces to the repository and you could add/edit [wiki](https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis). Might be closer to your preferred workflow.

**Comment by MitjaNemec** [comment]
Also, you might want to look at the `description` and `description_full` fields in `metadata_source.json` for all the plugins. This text shows in the PCM

**Pull request merged**
